version: 2.1

jobs:
  prod_build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nishkaush/react ./client
      - run: docker build -t nishkaush/api ./server
      - run: docker build -t nishkaush/worker ./worker
      - run: docker build -t nishkaush/nginx ./nginx
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run: docker push nishkaush/react
      - run: docker push nishkaush/api
      - run: docker push nishkaush/worker
      - run: docker push nishkaush/nginx

workflows:
  complex_flow:
    jobs:
      - prod_build:
