version: 2.1

jobs:
  react_test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t app-testing -f ./client/Dockerfile.dev ./client
      - run: docker run -e="CI=true" app-testing npm run test

  prod_build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t nishkaush/react ./client
      - run: docker build -t nishkaush/api ./server
      - run: docker build -t nishkaush/worker ./worker
      - run: docker build -t nishkaush/nginx ./nginx
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}
      - run: docker push nishkaush/react
      - run: docker push nishkaush/api
      - run: docker push nishkaush/worker
      - run: docker push nishkaush/nginx

workflows:
  complex_shit_flow:
    jobs:
      - react_test
      - prod_build:
          requires:
            - react_test
