version: 2.1

jobs:
  login_to_docker:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run: echo ${DOCKER_PASSWORD} | echo ${DOCKER_USERNAME}
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin

workflows:
  checking_docker_flow:
    jobs:
      - login_to_docker
