version: 2.1

jobs:
  react_test:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -f ./client/Dockerfile.dev -t app-testing
      - run: docker run -e="CI=true" app-testing npm run test

  prod_build:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - checkout
      - setup_remote_docker
      - run: docker build -t react-prod ./client
      - run: docker build -t api-prod ./server
      - run: docker build -t worker-prod ./worker
      - run: docker build -t nginx-prod ./nginx
      - run: echo $DOCKER_PASSWORD | docker login -u $DOCKER_USERNAME --password-stdin
      - run: docker push react-prod
      - run: docker push api-prod
      - run: docker push worker-prod
      - run: docker push nginx-prod

workflows:
  complex_shit_flow:
    jobs:
      - react_test
      - prod_build:
          requires:
            - react_test
