version: 2.1

jobs:
  login_to_docker:
    docker:
      - image: docker:17.05.0-ce-git
    steps:
      - setup_remote_docker
      - run: docker login -u ${DOCKER_USERNAME} -p ${DOCKER_PASSWORD}

workflows:
  checking_docker_flow:
    jobs:
      - login_to_docker
